### ISSUE TITLE
Effect on oEmbed discovery

### ISSUE THREAD

**Issue by johnbillion** [swissspidy/oEmbed-API#126]
[This line](https://github.com/swissspidy/oEmbed-API/blob/0.8.0/includes/default-filters.php#L63) has a considerable effect on the behaviour of oEmbeds in WordPress.

It means that oEmbed discovery is enabled for any URL that's placed onto its own line in post content, but the oEmbed API plugin only handles sanitisation of `iframe`s in `wp_filter_oembed_result()`.

If a URL provides an oEmbed link in its header but uses something other than `rich` for its oEmbed type, what happens? Does the sky fall down?

See also https://core.trac.wordpress.org/ticket/31975

**Comment by iparamonau** [comment]
Hi guys, Ivan from Iframely here. We're are an oEmbed aggregator. Been watching your work unfold with the same question in mind: how *we* will support auto-discovery of the new WP embeds. 

Basically, it gets down to this very issue reported @johnbillion for us as well.

For example, custom domains of Tumblr are easy for us - we just white-list based on oEmebed auto-discovery endpoint of Tumblr. 

Wordpress.com - same thing even for custom domains. All API calls go to public-api.wordpress.com which we can trust.

For this new plugin, all endpoints will be custom. But we do want to trust the plugin itself.

So, perhaps we could get a signature field of sorts in oEmbed JSON data so that we can allow embeds based on it?

For example, once we discover the oEmbed link that looks like it belongs to your plugin, we could add a get param that your API can re-iterate back to us in the response JSON.

**Comment by swissspidy** [comment]
> This line has a considerable effect on the behaviour of oEmbeds in WordPress.

That's why we're very strictly checking the resulting HTML.

> If a URL provides an oEmbed link in its header but uses something other than rich for its oEmbed type, what happens? Does the sky fall down?

If there's no `<iframe>`, the resulting HTML is empty and the behaviour is the same as before: The URL is simply shown on the site. Like when trying to embed something from a tumblr site with a custom domain or a site that uses the `photo` type.

> For this new plugin, all endpoints will be custom. But we do want to trust the plugin itself.

The same goes for the REST API. I wonder how people solve it there.

> So, perhaps we could get a signature field of sorts in oEmbed JSON data so that we can allow embeds based on it?

Something like that could easily be faked.
