### ISSUE TITLE
Format responses

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#13]
The oEmbed spec allows various response types: photo, video, link and rich.

We can populate this through post formats (eheheh), or through auto-detecting the post content. Or maybe through a third option, if anyone has suggestions.

**Comment by swissspidy** [comment]
Ideas:

* Return `link` if `rich` (HTML) output is disabled or if we decide not to do that.
* Use `photo` and `video` for attachments of that type (if someone wants to embed an attachment..)
* Leave post formats open for now as these are often stored and styled differently by the theme.  
  Just in case, there are functions like `get_media_embedded_in_content` and `get_post_gallery` we could use.

**Comment by morganestes** [comment]
I think enabling the output filter in #14 would handle this for the most part. We can set up filters for attachments and return the correct oEmbed markup for each filetype. Instead of trying to handle every possible oEmbed combination at the start, this could be useful examples of filters in action.

**Comment by swissspidy** [comment]
Our default resource type is `rich`, which means the post can be embedded in an iframe. This is currently set up for posts, pages and attachments.

`link` is kinda irrelevant because we use `rich` for everything that is supported by the oEmbed API.

Supporting `photo` would mean that image attachments won't be able to get embedded in an iframe, since this only returns the URL to the image.

Resources of type `video` return the `html` required to embed a video player. This means we need the iframe to work for video attachments too, which I'm not sure how feasible/desirable that is. Perhaps this should be plugin territory altogether.

**Comment by swissspidy** [comment]
A quick reminder that we should display proper players for audio and video attachments before we propose a core merge.

**Comment by swissspidy** [comment]
Using `wp_video_shortcode` and `wp_audio_shortcode` results in a bloated template and lots of code (see `prepend_attachment` and `edit_form_image_editor` for similar implementations).

* We need to ensure we don't duplicate too much of the template
* How does a video/audio embed look like?
* How do we properly include the MediaElement.js scripts in the footer?

**Comment by swissspidy** [comment]
With audio and video attachments now properly displayed and the recent addition of a `link` fallback, I think we are done here for the moment.
