### ISSUE TITLE
Indicating word count in the excerpt

### ISSUE THREAD

**Issue by danielbachhuber** [swissspidy/oEmbed-API#130]
Why is it helpful to include the word count? It seems out of place.

**Comment by swissspidy** [comment]
It has been part of the original mockups and has been part of our implementation ever since.

Showing a word count is not that uncommon for embeds. For example, when you post on Facebook from WordPress.com it shows the word count too.

Not against removing it if people don't like it but it definitely doesn't hurt and is easy to disable anyway.

**Comment by danielbachhuber** [comment]
I think it's a bit distracting, and haven't been a fan of the implementation on WordPress.com.

**Comment by kanenas** [comment]
@danielbachhuber :+1:

**Comment by swissspidy** [comment]
I created #136 for this so we all can play with it. Maybe we like it, maybe not.
