### ISSUE TITLE
Dynamic embed sizing

### ISSUE THREAD

**Issue by pento** [swissspidy/oEmbed-API#16]
We're looking at only embedding the first _n_ words in a post, but we don't know what that translates to in terms of pixels on the screen.

If we allowed JS, it'd be pretty easy for the iframe to send a message to the parent to say how tall it needs to be, we can't allow JS.

Is there another option, or is this going to be a blocker for the iframe method?

**Comment by swissspidy** [comment]
Looks like it is possible, but probably needs a `security="allow-scripts"` attribute because JS inside the iframe is required.

[There are libraries](https://github.com/davidjbradshaw/iframe-resizer) with great browser support, most of them use `MutationObserver` or `postMessage`.

Maybe the solution is sandboxing the oEmbed result just as the editor does in `wpView`. Perhaps someone with editor expertise can tell us more about that?

**Comment by mhmli** [comment]
Isn't this already done by the Facebook embed?

**Comment by pento** [comment]
iframe-resizer seems fairly hefty for our purposes. All we really need is for the iframe to calculate its own size, then `postMessage` it to the container window. The container window can sanity check the values, then resize the iframe.

**Comment by swissspidy** [comment]
Played around with this a bit. Haven't figured out an elegant way to detect which iframe has sent the data. Perhaps we need to do something like the following:

Iterate through all iframes on the site -> ask iframe for its size -> iframe responds -> update height.
