### ISSUE TITLE
Remove legacy code from `get_oembed_endpoint_url`

### ISSUE THREAD

**Issue by pfefferle** [swissspidy/oEmbed-API#58]
@swissspidy and I had a discussion about to remove the legacy code (`$url = add_query_arg( array( 'oembed' => 'true' ), home_url( '/' ) );`) from the `get_oembed_endpoint_url ` and use the `oembed_endpoint_url ` filter instead, or to keep it as is.

Any suggestions?

**Comment by swissspidy** [comment]
I let this aside for a bit to see how it goes, but at the moment we probably have better things to do than argue about the possible directions here :) Perhaps we should bring this up in the weekly chat.

It just feels overkill to introduce two new functions hooking into `get_oembed_endpoint_url`. The user won't have any idea how the function works when looking at the code because of the missing default URL, perhaps even thinking that it doesn't work right.

In my opinion, `$url = add_query_arg( array( 'oembed' => 'true' ), home_url( '/' ) );` is the default URL for the oEmbed endpoint and should therefore stay.

The

```php
if ( function_exists( 'rest_url' ) ) {
	$url = rest_url( 'wp/v2/oembed' );
}
```
 part _could_ be moved into another filter, but that means duplicating lots of code instead of keeping it simple like it now is.

**Comment by swissspidy** [comment]
Since the REST API has now officially been proposed for a merge, this means we can probably just use the REST API controller (and therefore `rest_url`) when we merge. So no need to put it in a filter and then back to the function again.

Closing this for now.
