### ISSUE TITLE
`secret` parameter not added to the iframe source

### ISSUE THREAD

**Issue by kanenas** [swissspidy/oEmbed-API#61]
<strong>WordPress Core</strong>: v.4.3
<strong>Theme</strong>: Twenty Fifteen (also test with Twenty Fifteen Child & Twenty Sixteen)
<strong>oEmbed API</strong>: v.0.5.0-20150909

When embedding inside posts or pages "Heading", "Site Title" & "Comments" links don't work.
No javascript errors when viewing with Google Chrome (v.45.0.2454.85 64-bit) & Mozilla Firefox (v.40.0.3) on Ubuntu 14.04.3 LTS.
No errors on debug.log
All the embedding posts are from the same domain.

*Examples*
http://www.my-soul.net/blog/%D0%B8%D1%85-%D0%B4%D0%B2%D0%B5-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC/

http://www.my-soul.net/blog/%CE%B1%CE%BA%CE%BF%CF%8D%CF%83%CE%B5%CE%B9-%CE%B4%CE%B9%CE%B1%CF%83%CF%86%CE%B1%CE%BB%CE%AF%CE%B6%CE%B5%CF%84%CE%B1%CE%B9-%CE%BC%CE%B5%CF%84%CE%B1%CE%B3%CE%BB%CF%89%CF%84%CE%B9%CF%83%CF%84%CE%AE%CF%82/

**Comment by swissspidy** [comment]
Thanks for your report, I'm gonna look into this!

At first sight, it seems the `secret` parameter isn't appended to the URL.

**Comment by swissspidy** [comment]
@kanenas I found the error and fixed it now. Embeds should work fine again when you update the plugin next time.

**Comment by kanenas** [comment]
@swissspidy, did you included in v.0.6.0? Because I downloaded a couple of hours ago and it didn't work.

**Comment by kanenas** [comment]
@swissspidy, just checked... I guess you haven't included the changes in v.0.6.0.

So I applied the 2 changes in files:
includes/default-filters.php
tests/test-plugin.php

Still doesn't work (you can check it out on my-soul.net) :(

**Comment by swissspidy** [comment]
Thanks for your quick response!

I suspect it's because of caching. I just tried embedding the following URLs on my dev site:

```
http://www.my-soul.net/blog/%d9%82%d8%af-%d8%af%d9%81%d9%91%d8%a9-%d8%a7%d9%84%d8%b9%d8%af%d9%91-%d8%a8%d9%88%d8%b2%d9%8a%d8%b1%d9%87%d8%a7-%d9%83%d9%85%d8%a7-%d8%a8%d9%80-%d9%88%d8%aa%d9%86%d8%a7%d9%85%d8%aa-%d8%a7%d9%84%d8%ae/
http://www.my-soul.net/blog/our-partners/
```

At first it didn't seem to work, but after I cleared the oEmbed cache, the security parameter was properly added I could click on the links.

Please try the following to temporarily disable the cache:

* Download the plugin here from GitHub, just to make sure everything is up-to-date
* Run the following in your database to remove cached oEmbed results:
```mysql
DELETE FROM wp_postmeta where meta_key LIKE '_oembed%'
```

* Put the following in a new file inside `wp-content/mu-plugns` (e.g. test.php):

```php
<?php
add_filter( 'embed_cache_oembed_types', '__return_empty_array' );
```

* Create a new post.
* Paste the URL to this new post in another post to embed it.

Now, after these steps clicking should work fine. If not, let me know and I'll have a look again.

**Comment by kanenas** [comment]
That's awesome! After <strong>deleting cached oEmbed results</strong> it worked a charm ;)
Just out of curiosity, how will <strong>WordPress</strong> users do the

```DELETE FROM wp_postmeta where meta_key LIKE '_oembed%'```

when updating through their <strong>WordPress Dashboard</strong>?

**Comment by swissspidy** [comment]
AFAIK WordPress normally _should_ clear/override the cache when updating the post so there shouldn't be a problem there. We don't have that many users yet anyway :)

Closing this now. Thanks again for your help.
