### ISSUE TITLE
sometimes the iFrame is 1px too small

### ISSUE THREAD

**Issue by FlorianBrinkmann** [swissspidy/oEmbed-API#76]
Hi again :)

In some cases the iFrame is 1px too small so the border at the bottom isn't displayed:

![oembed-etwas-zu-klein](https://cloud.githubusercontent.com/assets/2310924/9836298/5cafaee0-5a14-11e5-8ad9-76605fd45233.PNG)

Maybe you could add one or two pixel to the calculated iFrame height?
Edit: I use the latest Firefox on Windows10

**Comment by swissspidy** [comment]
> Maybe you could add one or two pixel to the calculated iFrame height?

No :) I rather want to fix the actual height calculation instead of adding a magic number.

Currently `document.querySelector( '.wp-embed' ) + 2` (2 is for the border, 2 * 1px) is used to get the window height inside the iframe. What does that return in your case and what's the actual height attribute?

Can you try changing that to `document.body.clientHeight` to see if the problem still occurs?

Relevant line: https://github.com/swissspidy/oEmbed-API/blob/master/includes/template.php#L307

**Comment by FlorianBrinkmann** [comment]
The value of `embed.clientHeight + 2` is equal to the value in the `height` attribute: 623px. Changing this to `document.body.clientHeight` hasn't changed anything. Then I tried to increase the `+2` to `+3` but the result was the same: 623px …

**Comment by swissspidy** [comment]
Hmm is this page somewhere live so I can test this myself?

Also, does it only happen in Firefox on Windows 10 or other browsers / operating systems as well?

**Comment by FlorianBrinkmann** [comment]
No, it's not live yet. I have tried to embed this site in another post and there the height is calculated correctly. In IE10 the embed in the post draft looks good.

**Comment by FlorianBrinkmann** [comment]
If I delete the featured image in the dev tools of Firefox, the height is calculated correctly and the border is displayed.

**Comment by FlorianBrinkmann** [comment]
For the embed in this post (http://florianbrinkmann.de/1392/wordpress-wochenrueckblick-kw-36-shortcode-roadmap-term-meta-und-mehr/) Firefox has the height value of 726 and IE10 the value of 727px.

**Comment by swissspidy** [comment]
Sounds like a rounding issue. Can you try out the pull request #80 to see if that fixes the problem? It always rounds the height up.

**Comment by FlorianBrinkmann** [comment]
I have updated the `template.php` but the result is the same. And when I install the latest version from the WordPress Backend, the embed is broken.

**Comment by swissspidy** [comment]
> I have updated the template.php but the result is the same.

Hmm that's difficult to test for me, since here it worked fine already in FF on Win 10. I will give it another try.

> And when I install the latest version from the WordPress Backend, the embed is broken.

That doesn't sound good... Can you elaborate what part is exactly broken? The API endpoint td http://florianbrinkmann.de/?oembed=true or the HTML site to be embedded (`/embed/`)?

**Comment by FlorianBrinkmann** [comment]
The HTML:

![unbenannt](https://cloud.githubusercontent.com/assets/2310924/9837280/4e6c614a-5a3a-11e5-8c2b-9ada2a1ff725.PNG)

**Comment by swissspidy** [comment]
I suppose you just downgraded the plugin again? :worried: Because now everything looks good. Where does the error happen?

http://florianbrinkmann.de/1339/twenty-sixteen-das-neue-standard-theme-fuer-wordpress-in-der-kurzvorstellung/embed/ looks good, http://florianbrinkmann.de/?oembed=true&url=http://florianbrinkmann.de/1339/twenty-sixteen-das-neue-standard-theme-fuer-wordpress-in-der-kurzvorstellung/ too.

Which URL is referenced in the iframe `src` attribute?
Have you tried re-saving your permalink settings?
Disabling other plugins?

I can only _guess_ what the error is without this information or a test site, sorry. I _assume_ that 3253c9c4589d46cfec19ae545e9d910e0427d443 did cause this, but don't know for sure.

**Comment by FlorianBrinkmann** [comment]
I upgraded again, you can see it here: http://florianbrinkmann.de/1392/wordpress-wochenrueckblick-kw-36-shortcode-roadmap-term-meta-und-mehr/

**Comment by FlorianBrinkmann** [comment]
Disabling other plugins and re-saving the permalinks didn't help.

**Comment by swissspidy** [comment]
@FlorianBrinkmann That particular issue has been fixed in 13e82bb18684853025039b60f0d852fc4f98c7dd

Now we can get back to the height issue.

**Comment by FlorianBrinkmann** [comment]
Yeah, actual I have the problem that in Firefox the iFrame is completly empty, I have opened another issue for that ...  #81

**Comment by FlorianBrinkmann** [comment]
I don't know if it helps, but when I resize the viewport so that the website has to resize too, the border at the bottom is displayed (when I resize it very slowly I can see points where it is hidden again but it works most of the time).
