### ISSUE TITLE
REST API Controller Audit

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#77]
Are we _\_doing\_it\_right_ everywhere?

**Comment by danielbachhuber** [comment]
I understand the intention of wanting to have an API endpoint. However, using the API endpoint to return an embedded HTML representation of the resource violates some principles of REST.

cc @rmccue @rachelbaker @joehoyle to see what opinions they have on a more "proper" implementation.

**Comment by swissspidy** [comment]
> However, using the API endpoint to return an embedded HTML representation of the resource violates some principles of REST.

The endpoint is used to return the oEmbed response data, not the embedded HTML. Example (without the REST API enabled, but response is the same):  http://pascalbirchler.ch/?oembed=true&url=http://pascalbirchler.ch/2015/08/23/wordcamp-schweiz-2015/

**Comment by swissspidy** [comment]
The reason we created the `WP_REST_oEmbed_Controller` class was for not duplicating efforts in the event of WP-API being integrated into core.

**Comment by swissspidy** [comment]
This is the code in question:

https://github.com/swissspidy/oEmbed-API/blob/master/includes/class-wp-rest-oembed-controller.php
https://github.com/swissspidy/oEmbed-API/blob/master/includes/functions.php#L279-L329

As the merge proposal is out, I'd love to get the team's opinion on it to see if it makes sense to have this functionality when oEmbed would be merged too.

Pinging @danielbachhuber @rmccue @rachelbaker @joehoyle

**Comment by joehoyle** [comment]
Hey @swissspidy, 

Some feedback from myself:

1. `WP_REST_oEmbed_Controller` should extends `WP_REST_Controller` given you are implement the same methods etc. This will probably give you a strict warning for the type declarations on `get_item` however, so you'd need to remove that. This is because technically it doesn't _have_ to be a `WP_REST_Request` which is passed to the callback. 

1. Having `format` as a one-off param is a little odd, did you consider reading form the `Accept` header instead, which is a bit closer to clean HTTP design? At some point it's possible the REST API will support different response formats and I'd imagine that's what we'd use.

1. Once you extend `WP_REST_Controller` then you'd be better to point the `schema` property of the route registration to `get_public_item_schema`, see https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-post-types-controller.php#L20, this will mean down the line you can use some internal declarations on the schema.

1. The schema object title (https://github.com/swissspidy/oEmbed-API/blob/master/includes/class-wp-rest-oembed-controller.php#L79) should be be lower with dashes, though given this is a noun, `oembed` might be better than `oembed-response`, everything is always a response.

1. `version` probably doesn't make to say `Always 1.0.`, seems like this will only be potentially missed in the future when a new version is introduced.

Hope that helps!

**Comment by rmccue** [comment]
Thoughts contained within. :)

> I understand the intention of wanting to have an API endpoint. However, using the API endpoint to return an embedded HTML representation of the resource violates some principles of REST.

I don't think it's too bad; we do similar for posts and such with `content`.

> `WP_REST_oEmbed_Controller` should extends `WP_REST_Controller` given you are implement the same methods etc.

Note that the base controller might not be merged with the infrastructure, as it's part of the endpoints. I'd leave it as-is for now, and mark the class `final` so you can do it later.

> Having format as a one-off `param` is a little odd, did you consider reading form the Accept header instead, which is a bit closer to clean HTTP design?

This is part of the oEmbed specification, IIRC, so unlikely to change. I think it's fine here. If you _can_ change it though, might be cool to have a generic `WP_REST_Server_XML` or something.

----

Your `rest_ensure_response` call is redundant, you can just return the data instead. :)

Rather than checking the format inside your endpoint, I'd recommend checking it back up in your request hook function, as it's a "metaparam" that affects the output, but isn't really part of the endpoint proper.

Otherwise, :+1:

**Comment by swissspidy** [comment]
Thanks for your feedback so far folks!

I created #115 now that does the following so far:

* Marks `WP_REST_oEmbed_Controller` as final
* Moves the format check outside the endpoint
* Adds the changes to the schema suggested by @joehoyle 
* Removes redundant `rest_ensure_response` call

> > Having format as a one-off param is a little odd, did you consider reading form the Accept header instead, which is a bit closer to clean HTTP design?

> This is part of the oEmbed specification, IIRC, so unlikely to change. I think it's fine here. If you can change it though, might be cool to have a generic `WP_REST_Server_XML` or something.

Correct, it's part of the specification. However, some oEmbed providers like [MetaCDN](http://www.metacdn.com/apidocs/oEmbed) do that as well so we might consider it in addition to the GET param. But if that's gonna make it into the REST API anyway at some point, we can also wait :)

We went the `rest_pre_serve_request` route because it also works with our legacy controller. Extending `WP_REST_Server` seems a bit overkill because it looks like we would need to completely override the  `serve_request` method.
