### ISSUE TITLE
Pull request workflow?

### ISSUE THREAD

**Issue by danielbachhuber** [swissspidy/oEmbed-API#79]
Might I suggest following a pull request workflow, [similar to this one](https://github.com/fusioneng/tech-docs/blob/master/tools/github.md#pull-requests) for all code changes to the project?

It will make it easier for other developers to follow and comment on code changes to the project.

**Comment by swissspidy** [comment]
Indeed that would make things easier. So far I haven't done it here, mainly because I was often working on the project for a couple of hours straight and it was faster.

However, I'm willing to change this and the guide you're linking to is really helpful. We could refer to it in a `CONTRIBUTING.md` file.
