### ISSUE TITLE
Improve the way the plugin deal with some particular cases (deleted post/edited slug)

### ISSUE THREAD

**Issue by imath** [swissspidy/oEmbed-API#96]
Hi,

I'm sorry i don't know enough yet about this plugin to suggest a patch. I've just tested this:

On Site A, i've embed a post of Site B, both are WordPress powered.

When i delete the post from Site B, the iframe is displaying the site's B 404.php full template.
When i edit the site's B post slug, the iframe is displaying the site's single.php full template.

**Comment by swissspidy** [comment]
Thanks for your report! I think those are absolutely valid questions.

**Post deletion:** I think a 404 notice inside the iframe would be preferable, but of course not the full 404.php template. WIll work on this :)

**Slug editing:** Normally `wp_old_slug_redirect()` runs in this case, redirecting to the site with the new slug. I have to test that properly... And if the old slug can't be redirected (e.g. because of a permalink structure change or something), the 404 view would be a great fallback.

**Comment by kanenas** [comment]
@swissspidy, I think (and this is just a suggestion) that displaying the website's 404 isn't the best solution (even for performance).
Showing an (small) image (that is handled by the plugin) or some text would be better and with that you could also handle 403 & possible 500 errors.

**Comment by swissspidy** [comment]
@kanenas We don't have lots of possibilities as it's still an iframe. Showing a 404 in the same style as the normal content is the best we can do. It doesn't break completely and even resizing and click handling still works. We can't really handle 403 or 500 errors in the plugin. I mean, if you've got a 500, WordPress probably won't even run.

**Comment by kanenas** [comment]
@swissspidy, I was talking about the 403, 404, 500 errors of the websites you embed <strong>FROM</strong>, which are not always the same with the websites embedded <strong>TO</strong>.
:)

**Comment by swissspidy** [comment]
@kanenas I know, but we can't detect if the site referenced by the embed returns an error. Prove me wrong otherwise :)
